### ISSUE TITLE
[Request] Scale certain canvas filters and overlays to match screen width

### ISSUE THREAD

**Issue by jshethbright** [Lyall/AISomniumFiles2Fix#2]
I noticed that certain UI elements, including the brightness filter, "fade-to-black" filter, or black filter, scale to fill on aspect ratio. This results in certain elements (especially the screen brightness filter) only applying to the center 16:9 portion of an ultrawide screen. I tried to mess around with finding which CanvasScaler links to these elements but couldn't figure it out. Would it be possible to scale these elements to fit the entire screen?

**Comment by jshethbright** [comment]
Never mind, found the filter elements and applied proper scaling to them, creating a separate repo on my own with these additional UI fixes.

**Comment by Lyall** [comment]
For what it's worth I've added a feature to the mod that _should_ address this. If you end up finding a better method and want to contribute to the mod, I'd gladly look through any pull requests.
